### ISSUE TITLE
AV: sdv format trace does not show sliced path

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#20] opened 2016-06-24 23:50 UTC
Each line in sdv format error trace is irrelevant.

To reproduce this issue,
`$(AddOns/AngelicVerifierNull/test/c-smack): python runtest.py t23.bpl --verifier-options="/sdv"`

Rename Angelic0.tt to defect.tt and run trace viewer.

**Comment by shuvendu-lahiri** [comment] 2016-06-27 21:26
Duplicate of #8

**Comment by shuvendu-lahiri** [comment] 2016-06-27 22:51
@Guoanshisb can you add the exact command line for avn.exe generated from the log for me to repro.

**Comment by Guoanshisb** [comment] 2016-06-28 00:06
@shuvendu-lahiri The command line I'm using is `AngelicVerifierNull.exe t23.harness.bpl /nodup /traceSlicing /copt:recursionBound:5 /copt:k:1 /copt:tryCTrace /sdv`

**Comment by Guoanshisb** [comment] 2016-06-28 20:49
will close after testing with sdvdefect.exe viewer with highlighting.

**Closed** 2016-06-29 22:09 UTC
Labels: duplicate
