### ISSUE TITLE
AV: EE does not give full cover

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#19] opened 2016-06-24 23:34 UTC
To reproduce this bug, inovoke AVN using the following command line argument.
`AngelicVerifierNull.exe t21.harness.bpl /nodup /traceSlicing /copt:recursionBound:5 /copt:k:1 /copt:tryCTrace /EE:ignoreAllAssumes- /EE:onlySlicAssumes- /EE:eeCoverOpt:1`

AV is supposed to infer `*y => x != NULL` so that the succeeding `if` block is not dead. However, it seems that even with `/EE:eeCoverOpt:1` enabled, EE infers `x != NULL` rather than the implication.

**Comment by shuvendu-lahiri** [comment] 2016-06-27 22:42
The issue is that (*y == NULL) does not match the filters and is thus pruned. But there was a bug in the filtering. 

If you now run the example with the additional flag 

``..\..\angelicVerifierNull\bin\debug\angelicVerifierNull.exe t21.harness.bpl /nodup /traceSlicing /copt:recursionBound:5 /copt:k:1 /copt:tryCTrace /EE:ignoreAllAssumes- /EE:onlySlicAssumes- /EE:eeCoverOpt:1 /EE:onlyDisplayAliasingInPre-``
It generates the Disjunctive cover and blocks the error without creating dead code. 

Can you create a regression with these specific flags? We can then close the issue.

**Comment by shuvendu-lahiri** [comment] 2016-06-27 23:08
closing.

**Closed by shuvendu-lahiri** 2016-06-27 23:08 UTC
