### ISSUE TITLE
Verification time difference with flag /tryCTrace

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/corral#46] opened 2017-05-24 20:01 UTC
Hi Akash,

I noticed that for the attached Boogie program, it takes around 40s on my machine to report an error trace without flags `/tryCTrace /noTraceOnDisk /printDataValues:1` while with them, it would take a long time.

The options I used are the following,
```
corral 205_updated.bpl /useProverEvaluate /cex:1 /k:1 /bopt:proverOpt:OPTIMIZE_FOR_BV=true /bopt:boolControlVC /timeLimit:880 /v:1 /maxStaticLoopBound:64 /recursionBound:65536 /irreducibleLoopUnroll:2 /trackAllVars /traceProgram:205_updated_trace.bpl
```

```
corral 205_updated.bpl /tryCTrace /noTraceOnDisk /printDataValues:1 /useProverEvaluate /cex:1 /k:1 /bopt:proverOpt:OPTIMIZE_FOR_BV=true /bopt:boolControlVC /timeLimit:880 /v:1 /maxStaticLoopBound:64 /recursionBound:65536 /irreducibleLoopUnroll:2 /trackAllVars /traceProgram:205_updated_trace.bpl
```

Shaobo
[205_updated.zip](https://github.com/boogie-org/corral/files/1027110/205_updated.zip)

**Comment by Guoanshisb** [comment] 2017-06-01 01:32
I also noticed that adding a call to `boogie_si_record` procedures could also make a big difference.

**Comment by akashlal** [comment] 2017-07-01 05:36
I can confirm that there is indeed a 4X time difference. In general, small changes in the Boogie code can result in different VCs and different Z3 time. I am unable to pinpoint the reason why this is happening.

**Comment by zvonimir** [comment] 2020-05-07 18:54
Let's close this one since it seems there is nothing much we can do about this.

**Closed by zvonimir** 2020-05-07 18:54 UTC
